(function() {var implementors = {};
implementors["optee_utee"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"enum\" href=\"optee_utee/enum.ErrorKind.html\" title=\"enum optee_utee::ErrorKind\">ErrorKind</a>&gt; for <a class=\"struct\" href=\"optee_utee/struct.Error.html\" title=\"struct optee_utee::Error\">Error</a>",synthetic:false,types:["optee_utee::error::Error"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u32.html\">u32</a>&gt; for <a class=\"struct\" href=\"optee_utee/struct.ParamTypes.html\" title=\"struct optee_utee::ParamTypes\">ParamTypes</a>",synthetic:false,types:["optee_utee::parameter::ParamTypes"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u32.html\">u32</a>&gt; for <a class=\"enum\" href=\"optee_utee/enum.ParamType.html\" title=\"enum optee_utee::ParamType\">ParamType</a>",synthetic:false,types:["optee_utee::parameter::ParamType"]},{text:"impl&lt;'attrref&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"optee_utee/object/struct.AttributeMemref.html\" title=\"struct optee_utee::object::AttributeMemref\">AttributeMemref</a>&lt;'attrref&gt;&gt; for <a class=\"struct\" href=\"optee_utee/object/struct.Attribute.html\" title=\"struct optee_utee::object::Attribute\">Attribute</a>",synthetic:false,types:["optee_utee::object::Attribute"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"optee_utee/object/struct.AttributeValue.html\" title=\"struct optee_utee::object::AttributeValue\">AttributeValue</a>&gt; for <a class=\"struct\" href=\"optee_utee/object/struct.Attribute.html\" title=\"struct optee_utee::object::Attribute\">Attribute</a>",synthetic:false,types:["optee_utee::object::Attribute"]},];
implementors["uuid"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"uuid/struct.Uuid.html\" title=\"struct uuid::Uuid\">Uuid</a>&gt; for <a class=\"struct\" href=\"uuid/adapter/struct.Hyphenated.html\" title=\"struct uuid::adapter::Hyphenated\">Hyphenated</a>",synthetic:false,types:["uuid::adapter::Hyphenated"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;&amp;'a <a class=\"struct\" href=\"uuid/struct.Uuid.html\" title=\"struct uuid::Uuid\">Uuid</a>&gt; for <a class=\"struct\" href=\"uuid/adapter/struct.HyphenatedRef.html\" title=\"struct uuid::adapter::HyphenatedRef\">HyphenatedRef</a>&lt;'a&gt;",synthetic:false,types:["uuid::adapter::HyphenatedRef"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"uuid/struct.Uuid.html\" title=\"struct uuid::Uuid\">Uuid</a>&gt; for <a class=\"struct\" href=\"uuid/adapter/struct.Simple.html\" title=\"struct uuid::adapter::Simple\">Simple</a>",synthetic:false,types:["uuid::adapter::Simple"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;&amp;'a <a class=\"struct\" href=\"uuid/struct.Uuid.html\" title=\"struct uuid::Uuid\">Uuid</a>&gt; for <a class=\"struct\" href=\"uuid/adapter/struct.SimpleRef.html\" title=\"struct uuid::adapter::SimpleRef\">SimpleRef</a>&lt;'a&gt;",synthetic:false,types:["uuid::adapter::SimpleRef"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"uuid/struct.Uuid.html\" title=\"struct uuid::Uuid\">Uuid</a>&gt; for <a class=\"struct\" href=\"uuid/adapter/struct.Urn.html\" title=\"struct uuid::adapter::Urn\">Urn</a>",synthetic:false,types:["uuid::adapter::Urn"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;&amp;'a <a class=\"struct\" href=\"uuid/struct.Uuid.html\" title=\"struct uuid::Uuid\">Uuid</a>&gt; for <a class=\"struct\" href=\"uuid/adapter/struct.UrnRef.html\" title=\"struct uuid::adapter::UrnRef\">UrnRef</a>&lt;'a&gt;",synthetic:false,types:["uuid::adapter::UrnRef"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
